#python 3.11을 포함한 베이스 이미지 사용
FROM python:3.11

#작업 데렉토리 설정
WORKDIR /app

#필요한 패키지들 설치
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

#코드 전체 복사
COPY . .

#tmp 디렉토리 생성
RUN mkdir -p /app/tmp


#FastAPI 앱 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8787"]